### ISSUE TITLE
Milliseconds are represented separately even when "detailed" is set to False

### ISSUE THREAD

**Issue by edigaryev** [xolox/python-humanfriendly#10]
Hi,

The documentation says:

>detailed – If True milliseconds are represented separately instead of being represented as fractional seconds (defaults to False).

But in some cases milliseconds are displayed anyway:

``` python
>>> import humanfriendly as hf

>>> hf.format_timespan(59.99)
'59.99 seconds'

>>> hf.format_timespan(61.10)
'1 minute, 1 second and 100 milliseconds'

>>> hf.format_timespan(61.10, False)
'1 minute, 1 second and 100 milliseconds'

>>> hf.format_timespan(3600 * 123 + .456)
'5 days, 3 hours and 456 milliseconds'
```

**Comment by xolox** [comment]
Hi Nikolay and thanks for the clear bug report, this issue should now be fixed! I first [wrote tests](https://travis-ci.org/xolox/python-humanfriendly/builds/163512693) that reproduce issues #10 and #11 and then [fixed both](https://travis-ci.org/xolox/python-humanfriendly/builds/163513409) (and needed to [restore](https://travis-ci.org/xolox/python-humanfriendly/builds/163515386) Python 2.6 compatibility).
