### ISSUE TITLE
Loss of precision when formatting timespans

### ISSUE THREAD

**Issue by edigaryev** [xolox/python-humanfriendly#11]
Hi,

Some test cases:

```
>>> import humanfriendly as hf

>>> hf.format_timespan(60.300)
'1 minute and 299 milliseconds'

>>> hf.format_timespan(300.300)
'5 minutes and 300 milliseconds'

>>> hf.format_timespan(1.015, True)
'1 second and 14 milliseconds'

>>> hf.format_timespan(10.015, True)
'10 seconds and 15 milliseconds'
```

**Comment by xolox** [comment]
Hi Nikolay and thanks for the clear bug report, this issue should now be fixed! I first [wrote tests](https://travis-ci.org/xolox/python-humanfriendly/builds/163512693) that reproduce issues #10 and #11 and then [fixed both](https://travis-ci.org/xolox/python-humanfriendly/builds/163513409) (and needed to [restore](https://travis-ci.org/xolox/python-humanfriendly/builds/163515386) Python 2.6 compatibility).
