### ISSUE TITLE
[FR] more color ?

### ISSUE THREAD

**Issue by Cologler** [xolox/python-humanfriendly#21]
`https://www.wikiwand.com/en/ANSI_escape_code#/Colors` show there are 16 colors.

why does `python-humanfriendly` only support 8 colors:

https://github.com/xolox/python-humanfriendly/blob/202b2a65dfc7ec9062c1f2915da3b5d284eaefb9/humanfriendly/terminal.py#L56

**Comment by xolox** [comment]
Hi and thanks for the feature request. I've just released version 4.6 which adds support for the eight high-intensity colors using `ansi_style(color=name, bright=True)`. Combined with the default colors and the faint colors (available using `ansi_style(color=name, faint=True)`) this brings the total number of supported colors to around 24.
