### ISSUE TITLE
Add changelog to releases please

### ISSUE THREAD

**Issue by pjnagel** [xolox/python-humanfriendly#23]
I could not find a changelog for this project. I looked for one in the following places:

- On the [pypi page](https://pypi.python.org/pypi/humanfriendly/4.7)
- In [the docs at readthedocs.io](https://humanfriendly.readthedocs.io/en/latest/)
- As a NEWS, Changelog etc. file on github in the root of the source code, or under docs/

Reason for the request: when I upgrade my projects to the latest versions of the libraries I use, I skim the changelog to see if there is any important new functionality, so I can know if there are any important refactorings of my code that I can now do, or just for future reference.

Without changelog lots of new functionality will just go unused - I only intensively read docs the first time I start using a library, not at every release.

**Comment by xolox** [comment]
Hi Pieter and thanks for the feedback. A changelog is now available on [GitHub](https://github.com/xolox/python-humanfriendly/blob/master/CHANGELOG.rst#release-411-2018-03-31) and [Read the Docs](http://humanfriendly.readthedocs.io/en/latest/changelog.html#release-4-11-2018-03-31).

**Comment by pjnagel** [comment]
"I’ve held off on having to keep track of changelogs in my open source programming projects until now (2018) because it’s yet another piece of bookkeeping that adds overhead to project maintenance versus just writing the damn code and throwing it up on GitHub :-p"

Think of it instead as proudly announcing the existence of your much-loved code-children to the world ;-)

Anyway, much thanks.
