### ISSUE TITLE
Add a serial comma version of `humanfriendly.text.concatenate`

### ISSUE THREAD

**Issue by slippycheeze** [xolox/python-humanfriendly#30]
While the use of the [serial (or Oxford) comma](https://en.wikipedia.org/wiki/Serial_comma) is a [contentious issue](https://thewritelife.com/is-the-oxford-comma-necessary/), it is also a popular enough choice that it would be nice to have it supported.  I'd certainly be very happy to see the `humanfriendly.text.concatenate` extended to add it:

 * `final_sep=""`, which could be set to `","` for a serial comma person, or
 * `serial_comma=False`, which could be set to `True` for the same effect, as well as
 * `conjunction="and"`, which could be set to, for example, `"or"` to produce a list with that effect.

alternately, support only the conjunction, but set the default to `" and"`, and allow `", and"` to produce an serial comma list.

...er, and perhaps come up with better names than I did for keyword parameters, as that is ... not my strongest skill. :)

**Comment by xolox** [comment]
Hi Daniel, thanks for the feedback and sorry for the late response.

I've just published [humanfriendly 9.0](https://humanfriendly.readthedocs.io/en/latest/changelog.html#release-9-0-2020-12-01) which adds the optional keyword arguments that you suggested.

Cheers!

<sup>(I'm not very good at naming things either :wink:)</sup>
