### ISSUE TITLE
Formatting large negative numbers minor issue

### ISSUE THREAD

**Issue by pernlofgren** [xolox/python-humanfriendly#40]
Noticed that the function `format_number` returns a a leading comma after the minus sign for negative numbers with a set of digits that is a multiple of 3. Just wanted to flag here in case it was unknown :) 

Current behaviour:
```python
difference = -285.671623847
humanfriendly.format_number(difference)
Out[118]: '-,285.67'
```
Expected behaviour:
```python
difference = -285.671623847
humanfriendly.format_number(difference)
Out[118]: '-285.67'
```

**Comment by xolox** [comment]
Hi Pernilla, thanks for the feedback and sorry for the late response.

I've just published [humanfriendly 9.0](https://humanfriendly.readthedocs.io/en/latest/changelog.html#release-9-0-2020-12-01) which fixes the issue you reported.

Cheers!
