### ISSUE TITLE
Dependency on pyreadline may cause breaking incompatibility in Python 3.9

### ISSUE THREAD

**Issue by brawner** [xolox/python-humanfriendly#44]
We've been noticing a deprecation warning in our python stack due to `pyreadline`, which is a dependency of this package. Unfortunately, `pyreadline` has not been updated in quite a bit and is likely abandoned at this point, which yields little hope the deprecation will be resolved by the release date of Python 3.9. It might make sense to remove the dependency on `pyreadline` for Windows with Python `>= 3.9`

Upstream issue for collections deprecation
https://github.com/pyreadline/pyreadline/issues/65

**Comment by aggieNick02** [comment]
The upstream issue notes that this is currently a hard break in python 3.10. I'd like to use humanfriendly on windows for some simple parsing of file size strings, but having to add abandoned pyreadline and knowing it'll break with python 3.10 is more trouble than the benefits of not reinventing a small wheel. :-)

**Comment by xolox** [comment]
https://github.com/xolox/python-humanfriendly/pull/45 has now been merged so this issue should be resolved.
