### ISSUE TITLE
Please do not import unittest

### ISSUE THREAD

**Issue by tomasz-sternumiot** [xolox/python-humanfriendly#53]
Great project!

Could you please do not import `unittest` framework in the library code?

https://github.com/xolox/python-humanfriendly/blob/1abbe85eb281fca17ae1cb769d0a23acdd2e1bd8/humanfriendly/compat.py#L68

Thank you!

**Comment by xolox** [comment]
This is fixed in [version 10.0](https://humanfriendly.readthedocs.io/en/latest/changelog.html#release-10-0-2021-09-17) that was just released.
